server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

# Route to Wallet Microservice
spring.cloud.gateway.routes[0].id=wallet-service
spring.cloud.gateway.routes[0].uri=lb://wallet-microservice
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/wallets/**

# Route to Inventory Microservice
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=lb://inventory-microservice
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/inventory/**

# Route to Shop Microservice
spring.cloud.gateway.routes[2].id=shop-service
spring.cloud.gateway.routes[2].uri=lb://shop-microservice
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/products/**

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG